version: '3.1'

services:
  main:
    image: oskardudycz/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
